version: '3.8'

services:
  parts-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parts-api-container
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - parts-network

  redis:
    image: "redis:latest"
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - parts-network

networks:
  parts-network:
    driver: bridge
